# -*- coding: utf-8 -*-
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = '$project_title$'
copyright = '2021'
author = 'laurent'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.githubpages',
]

extensions = ['sphinx.ext.autodoc', 'sphinx.ext.doctest', 'sphinx.ext.intersphinx', 'sphinx.ext.todo',
              'sphinx.ext.coverage', 'sphinx.ext.mathjax', 'sphinx.ext.ifconfig', 'sphinx.ext.viewcode',
              'sphinx.ext.githubpages',
              'sphinx_panels'
              ]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

html_css_files = ['custom.css',
                  'https://example.com/css/custom.css',
                  ('print.css', {'media': 'print'})]

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}
nosidebar = True
# ---sphinx-themes-----

from enum import Enum,auto

class StyleEnum:
    yummy = auto()
    stanford=auto()
    greycreme=auto()


choice = StyleEnum.yummy

# html_theme = 'alabaster'
# html_theme = 'bootstrap-astropy'

if choice == StyleEnum.yummy:
    html_theme = 'yummy_sphinx_theme'

elif choice == StyleEnum.stanford:
    import sphinx_theme
    html_theme = 'stanford_theme'
    html_theme_path = [sphinx_theme.get_html_theme_path('stanford-theme')]
    from PSphinxTheme import utils
    p, html_theme, needs_sphinx = utils.set_psphinxtheme('p-red')
    html_theme_path = p

elif choice == StyleEnum.greycreme:
    html_theme = 'p-greycreme'
    from PSphinxTheme import utils
    p, html_theme, needs_sphinx = utils.set_psphinxtheme(html_theme)
    html_theme_path = p
else:
    raise RuntimeError("no style selected")



html_style = 'css/custom.css'


html_theme_options = {
    'navs': {
        #        'Home': 'http://tagnumelite.elitekast.com',
        #        'Blog': 'http://blog.elitekast.com',
        #        'Forum': 'http://forum.elitekast.com',
    },
    'github_url': 'TagnumElite/yummy_sphinx_theme',
    'bitbucket_url': 'TagnumElite/yummy_sphinx_theme',
    'gitlab_url': 'TagnumElite/yummy_sphinx_theme',
    # 'navbar_icon': 'spin fa-book',
    'jumbotron_use_geopattern': True,
    'nosidebar': True,
    'navbar_icon': 'music',
    'home_name': 'let\'s rock !'
}

latex_engine = 'pdflatex'
latex_elements = {

    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',
    'releasename': ' ',
    # Sonny, Lenny, Glenn, Conny, Rejne, Bjarne and Bjornstrup
    # 'fncychap': '\\usepackage[Lenny]{fncychap}',
    'fncychap': '\\usepackage{fncychap}',
    'fontpkg': '\\usepackage{amsmath,amsfonts,amssymb,amsthm}',

    'figure_align': 'htbp',
    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '10pt',

}
